### ISSUE TITLE
`kitikiplot.egg-info` and `dist` are included in repository

### ISSUE THREAD

**Issue by jewels86** [BodduSriPavan-111/kitikiplot#2]
Both of the above items are output from (what I think is) the `python -m build` command. Output files like that are generally set to be ignored by git so they don’t add clutter to the repository. Right now everything looks pretty clean though, so whether or not they’re ignored doesn’t really matter.

**Comment by BodduSriPavan-111** [comment]
> Both of the above items are output from (what I think is) the `python -m build` command. Output files like that are generally set to be ignored by git so they don’t add clutter to the repository. Right now everything looks pretty clean though, so whether or not they’re ignored doesn’t really matter.

Hi @jewels86,

Thank you for your valuable feedback on making the repository cleaner. I used the command: ```python setup.py sdist bdist_wheel``` to create distribution files. To improve the structure and avoid unnecessary clutter, removed ```kitikiplot.egg-info``` and ```dist``` from the repository and included them in the ```.gitignore``` file so that this will ensure, these generated files are excluded from future commits.

I’m closing this issue now. Feel free to reach out if you have any further suggestions.

Thanks again for your support!

Best regards,
Boddu Sri Pavan
